### ISSUE TITLE
Error 'ts-node' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by chinhdo** [ashleydavis/typescript-template#4]
Cloned the project and ran ```npm install```, etc. Then when I tried to run ```npm run start:dev``` I got this error:

``` bash
$ npm run start:dev

> twitter-bot@1.0.0 start:dev
> nodemon

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node ./src/cli.ts`
'ts-node' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...
```

I was able to get around it by running ```npm install -g ts-node```

**Comment by ashleydavis** [comment]
That's strange. I just got a fresh copy, did the `npm install` and `npm run start:dev` and it works ok for me.

I don't have ts-node installed globally, just the local version.

What version of Node.js / npm are you using?

**Comment by chinhdo** [comment]
Yeah it's strange. Somehow the local ts-node doesn't work for me. I can reproduce it after I run ```npm uninstall -g ts-node```, remove node_modules, run ```npm install``` again.

My versions:

```
$ npm --version
7.7.4

$ node --version
v14.16.0
```

**Comment by ashleydavis** [comment]
I'm not sure what you are having problems with it. Please let me know if you find a permanent answer that I could include in the code here.

**Comment by chinhdo** [comment]
@ashleydavis Sure if I find the root cause I'll definitely post back. I'll try to see if I can reproduce on another system. Thanks.

**Comment by Cardoso-topdev** [comment]
Hi @chinhdo !
I have the same problem. I've installed ts-node globally and locally, but it still shows error like this
`[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): '.\**\*.ts'
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `'ts-node' './main.ts'`
''ts-node'' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...
`

Have you solved your problem?
If so, please let me know your answer.
Thanks.

**Comment by ashleydavis** [comment]
What project are you running?

This repo doesn't even have a `main.ts`!

@Cardoso-topdev in your example it looks like ts-node is wrapped in quotes, would that be your problem?

**Comment by Cardoso-topdev** [comment]
Thank you for your kind reply. I solved this problem with editing script on package.json file. :)

**Comment by ShomaGujjar** [comment]
Running the following command fixed my problem:
npm install -D tslib @types/node

**Comment by kkratos** [comment]
installing ts-node globally worked for me.

**Comment by shreyasharma0201** [comment]
I have the same problem. When I globally install ts-node and typescript it doesn't work.
Later, I locally install then it worked for me.

[this may help](https://www.npmjs.com/package/ts-node)

**Comment by ashleydavis** [comment]
> I have the same problem. When I globally install ts-node and typescript it doesn't work. Later, I locally install then it worked for me.
> 
> [this may help](https://www.npmjs.com/package/ts-node)

You shouldn't globally install ts-node and TypeScript and this repo is not supposed to work that way.  

If you install global versions they are bound to be using different version than what this repo requires so you shouldn't be surprised if that doesn't work.

Please only install local versions using `npm install` inside your local copy of this repository.

If you need to, you can run local versions using `npx ts-node` and `npx tsc`.

**Comment by ashleydavis** [comment]
I've just noticed a problem like this happening with nodemon!

Here are the details:

https://github.com/remy/nodemon/issues/1951
